---
- name: All
  hosts: all

  tasks:
  # - name: "Apt | Upgrade all packages to the latest version"
  #   ansible.builtin.apt:
  #     name: "*"
  #     state: latest
  #     update_cache: true

  - name: Apt | update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    become: true

  - name: "Install Veracrypt"
    ansible.builtin.include_tasks: "tasks/instala_veracrypt.yml"
    when: veracrypt_version is defined
    tags: [veracrypt]

  - name: "Install rclone"
    ansible.builtin.include_tasks: "tasks/instala_rclone.yml"
    tags: [rclone]

  - name: "Install tlp"
    ansible.builtin.include_tasks: "tasks/install_tlp.yml"
    when: tlp_batteries is defined
    tags: [battery]

  - name: "Definir la variable python_venv_path"
    ansible.builtin.set_fact:
      python_venv: "{{ python_venv if python_venv is defined else '/usr/local/venv-ansible-{{ ansible_version.major }}.{{ ansible_version.minor }}' }}"

  - name: "Pip | Install requirements"
    ansible.builtin.pip:
      name:
        - github3.py
      virtualenv: "{{ python_venv }}"
      virtualenv_command: python3 -m venv
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: '1'
    when: python_venv is defined