---
  - hosts: devops
    become: true
    tags: devops

    tasks:
    - name: "Apt | instala aplicaciones Gnome"
      ansible.builtin.apt:
        name:
          - meld
          - zsh-static
          - tilix
          - tmux
        state: present
      become: true

    - name: "Ansible check file exists example"
      ansible.builtin.stat:
        path: /home/{{devops_user_name}}/.zim
      register: file_details

    - name: "Zsh | configuration of Zim - https://github.com/zimfw/zimfw"
      ansible.legacy.shell: curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
      become_user: "{{ devops_user_name }}"
      when: devops_shell == "zsh" and not file_details.stat.exists

    - name: "Zsh | make shell the default shell"
      ansible.builtin.user:
        name: "{{ devops_user_name }}"
        shell: "/bin/{{ devops_shell }}"

    - name: "Devops | Instala aplicaciones con snap"
      community.general.snap:
        name: "{{ item }}"
        classic: true
      with_items:
        - "{{ list_of_snap_devops }}"
      become: true
      tags:
        - devops
        - snap

    - name: "Install Ansible"
      ansible.builtin.include_tasks:
        file: tasks/devops_ansible.yml
      tags:
        - devops
        - ansible

    - name: "Kubeselect | Clone repo"
      ansible.builtin.git:
        repo: https://github.com/fatliverfreddy/kubeselect.git
        dest: /tmp/kubeselect
        version: master
      tags:
        - devops
        - kubernetes

    - name: "Kubeselect | Install"
      ansible.builtin.copy:
        dest: /usr/local/bin
        follow: false
        force: true
        group: root
        mode: "0755"
        owner: root
        src: /tmp/kubeselect/kubeselect
      tags:
        - devops
        - kubernetes

    - name: "Install kubectl"
      ansible.builtin.import_tasks:
        file: tasks/install_kubectl.yml
      tags:
        - devops
        - kubernetes

    - name: "Kubecolor | Get latest release"
      community.general.github_release:
        user: hidetatz
        repo: kubecolor
        action: latest_release
      register: kubecolor_github_release
      tags:
        - devops
        - kubernetes
        - kubecolor

    - name: "Kubecolor | Ensure directory exists"
      ansible.builtin.file:
        path: /tmp/kubecolor
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - devops
        - kubernetes
        - kubecolor

    - name: "Kubecolor | Extract some files"
      ansible.builtin.unarchive:
        src: "https://github.com/hidetatz/kubecolor/releases/download/{{ kubecolor_github_release.tag }}/kubecolor_{{ kubecolor_github_release.tag | regex_search('[0-9.]+') }}_Linux_x86_64.tar.gz"
        dest: /tmp/kubecolor
        remote_src: true
      tags:
        - devops
        - kubernetes
        - kubecolor

    - name: "Kubecolor | Install"
      ansible.builtin.copy:
        src: /tmp/kubecolor/kubecolor
        dest: /usr/local/bin
        owner: root
        group: root
        mode: "0755"
      tags:
        - devops
        - kubernetes
        - kubecolor

    - name: "Kubens | Get latest release"
      community.general.github_release:
        user: ahmetb
        repo: kubectx
        action: latest_release
      register: kubens_github_release
      tags:
        - devops
        - kubernetes
        - kubens

    - name: "Kubens | Install"
      ansible.builtin.get_url:
        url: https://github.com/ahmetb/kubectx/releases/download/{{ kubens_github_release.tag }}/kubens
        dest: /usr/local/bin/kubens
        owner: root
        group: root
        mode: "0755"
      tags:
        - devops
        - kubernetes
        - kubens

    - name: "K9S | Install"
      ansible.legacy.shell: curl -sS https://webinstall.dev/k9s | bash
      become_user: "{{ devops_user_name }}"
      tags:
        - devops
        - kubernetes
        - k9s

    # - name: "Install Lens"
    #   ansible.builtin.include_tasks:
    #     file: tasks/install_lens.yml
    #   tags:
    #     - devops
    #     - kubernetes

