---

- src: https://github.com/stefangweichinger/ansible-rclone.git
  # version: master
  scm: git
  name: ansible-rclone

- name:  ansible-role-firewall
  src: https://github.com/geerlingguy/ansible-role-firewall.git
  version: master
  scm: git