---

- src: https://github.com/stefangweichinger/ansible-rclone.git
  # version: master
  scm: git
  name: ansible-rclone

- name: ansible-role-firewall
  src: https://github.com/geerlingguy/ansible-role-firewall.git
  version: master
  scm: git

- name: ansible-role-protonvpn
  src: https://github.com/diademiemi/ansible_role_protonvpn.git
  scm: git