---
- name: Servidor
  hosts: servidor
  become: true

  tasks:

  - name: Servidor | requisito para el montaje de datos
    apt:
      name: dmraid
      state: present
    become: true

  - name: "Servidor | instalar herramienta de backup"
    apt:
      name: rsnapshot
      state: present
    become: true

  #- include_tasks: tasks/instala_osync.yml
