---

- name: devops | ansible | actualizar requerimientos
  ansible.builtin.pip:
    name:
      - molecule
      - setuptools
      - wheel
    virtualenv: "{{ python_venv | default('venv-ansible-{{ ansible_version }}') }}"
    virtualenv_command: python3 -m venv
    # virtualenv_python: "{{ python_version }}"
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: '1'
  tags:
    - devops
    - ansible

- name: devops | ansible | requerimiento para creación de VM en Vsphere
  ansible.builtin.pip:
    name:
      - pyvmomi
    virtualenv: "{{ python_venv | default('venv-ansible-{{ ansible_version }}') }}"
    virtualenv_command: python3 -m venv
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: '1'
  tags:
    - devops
    - ansible

- name: devops | script that allow read access to YAML files through command line
  ansible.builtin.pip:
    name:
      - shyaml
    virtualenv: "{{ python_venv | default('venv-ansible-{{ ansible_version }}') }}"
    virtualenv_command: python3 -m venv
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: '1'
  tags:
    - devops
    - ansible

# - name: devops | ansible install
#   ansible.builtin.pip:
#     name: ansible-core=={{ ansible_version_target | default('2.17.5') }}
#     virtualenv: "{{ python_venv | default('venv-ansible-{{ ansible_version }}') }}"
#     virtualenv_command: python3 -m venv
#   environment:
#     PIP_BREAK_SYSTEM_PACKAGES: '1'
#   tags:
#     - devops
#     - ansible

- name: devops | ansible | requerimiento para creación de streams en Graylog
  ansible.builtin.pip:
    name: jmespath
    virtualenv: "{{ python_venv | default('venv-ansible-{{ ansible_version }}') }}"
    virtualenv_command: python3 -m venv
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: '1'
  tags:
    - devops
    - ansible

    