---

- name: devops | ansible | instala molecule
  pip:
    name: molecule
    state: latest
    executable: /usr/local/bin/pip3
  become: true
  tags:
    - devops
    - ansible

- name: devops | ansible | requerimiento para creación de VM en Vsphere
  pip:
    name: pyvmomi
    state: latest
    executable: /usr/local/bin/pip3
  become: true
  tags:
    - devops
    - ansible

- name: devops | script that allow read access to YAML files through command line
  pip:
    name: shyaml
    state: latest
    executable: /usr/local/bin/pip3
  become: true
  tags:
    - devops

# - name: devops | ansible install
#   ansible.builtin.pip:
#     name: ansible-core=={{ ansible_version_install | default('2.16.3') }}
#     extra_args: --user
#     executable: /usr/local/bin/pip3
#   become: true
#   tags:
#     - devops

- name: devops | ansible | actualizar requerimientos
  pip:
    name: "{{ item }}"
    state: latest
    executable: /usr/local/bin/pip3
  loop:
    - setuptools
    - wheel
    - github3.py
  become: true
  tags:
    - devops

- name: devops | ansible | requerimiento para creación de streams en Graylog
  pip:
    name: jmespath

    state: latest
    executable: /usr/local/bin/pip3
  become: true
  tags:
    - devops

- name: Apt | requerimiento para creación de VM en Vsphere
  apt:
    name:
      - sshpass
    state: present
  become: true
  tags:
    - devops
    - ansible
    