
- name: Veracrypt | Check if VeraCrypt package is already downloaded
  stat:
    path: /tmp/veracrypt.deb
  register: veracrypt_deb

- name: Veracrypt | Download VeraCrypt
  get_url:
    url: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_version }}/+download/veracrypt-{{ veracrypt_version }}-Ubuntu-{{ ansible_distribution_version }}-amd64.deb"
    dest: /tmp/veracrypt.deb
    force: yes
  when: not veracrypt_deb.stat.exists

- name: Veracrypt | Calculate the SHA256 checksum of the downloaded file
  ansible.builtin.command: sha256sum /tmp/veracrypt.deb
  register: sha256_calculated

- name: Veracrypt | set veracryp_sha256_expected value
  set_fact:
    veracryp_sha256_current: "{{ veracryp_sha256_expected[ansible_distribution_version] }}"

- name: Veracrypt | Calculate the SHA256 checksum of the downloaded file
  assert:
    that:
    - "sha256_calculated.stdout.split()[0] == veracryp_sha256_current"
    fail_msg: "La suma de verificación SHA256 no coincide"
    success_msg: "La suma de verificación SHA256 coincide"

- name: Veracrypt | Install a .deb package
  ansible.builtin.apt:
    deb: /tmp/veracrypt.deb
  when: ansible_distribution == "Ubuntu" and sha256_calculated.stdout.split()[0] == veracryp_sha256_current
