
- name: "devops | kubectl | Get latest kubectl version"
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: version

- name: "devops | kubectl | Create kubectl versioned directory"
  ansible.builtin.file:
    path: /opt/kubectl-{{ version.content }}
    state: directory
  become: true

- name: "devops | kubectl | Download the latest kubectl release"
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/amd64/kubectl
    dest: /opt/kubectl-{{ version.content }}
  register: kubectl
  become: true

- name: "devops | kubectl | Download the kubectl checksum"
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/amd64/kubectl.sha256
    dest: /opt/kubectl-{{ version.content }}
  register: kubectl
  become: true

- name: "devops | kubectl | Get kubectl sha256sum"
  ansible.builtin.shell: sha256sum /opt/kubectl-{{ version.content }}/kubectl | cut -d " " -f1
  register: file_shasum

- ansible.builtin.set_fact:
    shasum1={{ file_shasum.stdout }}

# - ansible.builtin.debug: var=shasum1
#   run_once: true

- name: "devops | kubectl | Get sha256sum value from file"
  command: cat /opt/kubectl-{{ version.content }}/kubectl.sha256
  register: downloaded_shasum

- ansible.builtin.set_fact:
    shasum2={{ downloaded_shasum.stdout }}

# - ansible.builtin.debug: var=shasum2
#   run_once: true

- name: "devops | kubectl | Assert that the kube.builtin.filectl binary is OK"
  ansible.builtin.assert:
    that:
      - file_shasum.stdout == downloaded_shasum.stdout
    fail_msg: "Shasum does not correspond"
    success_msg: "kubectl shasum verified: ok"

- name: "devops | kubectl | Change kubectl file permission"
  ansible.builtin.file:
    path: "/opt/kubectl-{{ version.content }}/kubectl"
    mode: '0755'
  become: true

- name: "devops | kubectl | Ensure the file does not exist"
  ansible.builtin.file:
    path: "/usr/bin/kubectl"
    state: absent

- name: "devops | kubectl | Create a symlink to kubectl"
  ansible.builtin.file:
    src: "/opt/kubectl-{{ version.content }}/kubectl"
    dest: "/usr/bin/kubectl"
    state: link

